version: '3.8'

services:
  discord-capture:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: discord-capture
    env_file:
      - .env
    volumes:
      - .:/app
    command: ["python", "main.py"]
    ports:
      - "8101:8101"
    depends_on:
      - mock-agent
      - mock-publish

  mock-agent:
    build:
      context: ./mock
      dockerfile: Dockerfile.mock
    container_name: mock-agent
    command: ["python", "mock_agent.py"]
    ports:
      - "8201:8201"

  mock-publish:
    build:
      context: ./mock
      dockerfile: Dockerfile.mock
    container_name: mock-publish
    command: ["python", "mock_publish.py"]
    ports:
      - "8301:8301" 