import discord
import json
from typing import List


def build_discord_embeds_from_supplement_request(supplement_request: dict) -> List[discord.Embed]:
    """
    Build a list of Discord Embed objects from a SupplementRequest dict.
    Only includes Supplement Request and Spec Info cards.
    Returns: List[discord.Embed]
    """
    embeds = []
    # 1. 主问题/描述
    main_embed = discord.Embed(
        title="📝 Supplement Request",
        description=f"**{supplement_request.get('question', '')}**",
        color=discord.Color.purple()
    )
    main_embed.add_field(
        name="Event Info",
        value=(
            f"**Type:** `{supplement_request.get('event_type', '')}`\n"
            f"**Session:** `{supplement_request.get('session_id', '')}`\n"
            f"**Event ID:** `{supplement_request.get('event_id', '')}`"
        ),
        inline=False
    )
    main_embed.set_footer(text="Generated by Chatmill")
    embeds.append(main_embed)
    # 2. 任务信息
    spec = supplement_request.get("spec") or supplement_request.get("payload")
    if spec:
        spec_embed = discord.Embed(
            title="🗂️ Spec Info",
            color=discord.Color.blue()
        )
        spec_str = "\n".join([f"• **{k}**: {v}" for k, v in spec.items()])
        spec_embed.description = spec_str
        embeds.append(spec_embed)
    return embeds
