import discord
import json
from typing import List


def build_discord_embeds_from_supplement_request(supplement_request: dict) -> List[discord.Embed]:
    """
    Build a list of visually appealing Discord Embed objects from a SupplementRequest dict, splitting content into multiple themed embeds.
    Returns: List[discord.Embed]
    """
    embeds = []
    # 1. 主问题/描述
    main_embed = discord.Embed(
        title="📝 Supplement Request",
        description=f"**{supplement_request.get('question', '')}**",
        color=discord.Color.purple()
    )
    main_embed.add_field(
        name="Event Info",
        value=(
            f"**Type:** `{supplement_request.get('event_type', '')}`\n"
            f"**Session:** `{supplement_request.get('session_id', '')}`\n"
            f"**Event ID:** `{supplement_request.get('event_id', '')}`"
        ),
        inline=False
    )
    main_embed.set_footer(text="Generated by Chatmill")
    embeds.append(main_embed)
    # 2. 任务信息
    task = supplement_request.get("task") or supplement_request.get("payload")
    if task:
        task_embed = discord.Embed(
            title="🗂️ Task Info",
            color=discord.Color.blue()
        )
        task_str = "\n".join([f"• **{k}**: {v}" for k, v in task.items()])
        task_embed.description = task_str
        embeds.append(task_embed)
    # 3. 消息历史
    messages = supplement_request.get("messages", [])
    if messages:
        msg_embed = discord.Embed(
            title="💬 Messages",
            color=discord.Color.green()
        )
        msg_str = "\n".join([
            f"> **{m.get('author_name', '')}** [{m.get('timestamp', '')[:19].replace('T', ' ')}]: {m.get('content', '')}"
            for m in messages
        ])
        msg_embed.description = msg_str
        embeds.append(msg_embed)
    # 4. 其他字段
    skip_keys = {"question", "event_type", "session_id", "event_id", "task", "payload", "agent_profile", "messages"}
    other_fields = [(k, v) for k, v in supplement_request.items() if k not in skip_keys]
    if other_fields:
        other_embed = discord.Embed(
            title="🔹 Other Info",
            color=discord.Color.orange()
        )
        for k, v in other_fields:
            v_str = json.dumps(v, ensure_ascii=False, indent=2) if isinstance(v, (dict, list)) else str(v)
            other_embed.add_field(name=k, value=v_str[:1024], inline=False)
        embeds.append(other_embed)
    return embeds
